// DO NOT MODIFY BY HAND; code generated by a template.

using System.ServiceModel;

// ----------------------------------------------------------------------------	
// CatalogServiceClient abstractions
// ----------------------------------------------------------------------------	
public interface ICatalogServiceClient : ICatalogService, ICommunicationObject
{
}

public class CatalogServiceClientProxy : CatalogServiceClient, ICatalogServiceClient
{
}

public interface ICatalogServiceClientFactory
{
    ICatalogServiceClient BuildCatalogServiceClient();
}

public class CatalogServiceClientFactory : ICatalogServiceClientFactory
{
    public ICatalogServiceClient BuildCatalogServiceClient()
    {
        return new CatalogServiceClientProxy();
    }
}

